// Generated from the bundled demo PDFs. Regenerated by scripts/generate-demo-pdfs.py.
import type { UploadedFile } from './data'
export const sampleFiles: UploadedFile[] = [
  {
    "id": "sample-1",
    "name": "research-graph-demo-01.pdf",
    "size": 2662,
    "lastModified": 0
  },
  {
    "id": "sample-2",
    "name": "research-graph-demo-02.pdf",
    "size": 2656,
    "lastModified": 0
  },
  {
    "id": "sample-3",
    "name": "research-graph-demo-03.pdf",
    "size": 2708,
    "lastModified": 0
  },
  {
    "id": "sample-4",
    "name": "research-graph-demo-04.pdf",
    "size": 2627,
    "lastModified": 0
  },
  {
    "id": "sample-5",
    "name": "research-graph-demo-05.pdf",
    "size": 2673,
    "lastModified": 0
  },
  {
    "id": "sample-6",
    "name": "research-graph-demo-06.pdf",
    "size": 2677,
    "lastModified": 0
  },
  {
    "id": "sample-7",
    "name": "research-graph-demo-07.pdf",
    "size": 2636,
    "lastModified": 0
  },
  {
    "id": "sample-8",
    "name": "research-graph-demo-08.pdf",
    "size": 2677,
    "lastModified": 0
  }
]
